export const NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';
export const POST_SERVICE = 'POST_SERVICE';
export const CHAT_SERVICE = 'CHAT_SERVICE';
export const COUPLE_SERVICE = 'COUPLE_SERVICE';
export const USER_SERVICE = 'USER_SERVICE';
